# Generated by Django 2.1 on 2018-08-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_tagger',
            field=models.BooleanField(default=True),
        ),
    ]
